DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film_like_users;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa;

CREATE TABLE IF NOT EXISTS mpa (
id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL,
description varchar(200), 
release_date DATE,
mpa_id INTEGER REFERENCES mpa (id),
count_likes INTEGER,
duration INTEGER
); 

CREATE TABLE IF NOT EXISTS users (
id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
login varchar(50) NOT NULL,
name varchar(50),
email varchar(100), 
birthday DATE,
count_friends INTEGER
);

CREATE TABLE IF NOT EXISTS genres (
id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genre (
genre_id INTEGER REFERENCES genres (id),
film_id INTEGER REFERENCES films (id),
PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS likes (
film_id INTEGER REFERENCES films (id),
user_id INTEGER REFERENCES users (id),
PRIMARY KEY(film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
user_id INTEGER REFERENCES users (id),
friend_id INTEGER REFERENCES users (id),
status varchar(50),
PRIMARY KEY(user_id, friend_id)
);